name: Handle Signing Request
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  handle-request:
    permissions:
      contents: write
      issues: write

    if: contains(github.event.issue.labels.*.name, 'sign-request')

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Handle Signing Request
        # https://github.com/octokit/octokit.js/issues/2075 : temporary remove check
        # `--unstable``: to use Deno.HttpClient
        run: deno run --no-check=remote --allow-all --unstable --quiet repo/task/actions/handle-request/mod.ts repo ${{ github.token }}
