name: Handle Signing Request
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Minify and Publish files
        # https://github.com/octokit/octokit.js/issues/2075 : temporary remove check
        run: deno run --no-check=remote --allow-all --quiet repo/task/actions/onHandleRequest.ts repo ${{ github.token }}
