name: Handle Signing Request
on:
  issues:
    types:
      - opened
      - reopened

jobs:
  handle-request:
    permissions:
      contents: write
      issues: write

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Handle Signing Request
        # https://github.com/octokit/octokit.js/issues/2075 : temporary remove check
        run: deno run --no-check=remote --allow-all --quiet repo/task/actions/on-handle-request.ts repo ${{ github.token }}
