name: Test Workflow
on: workflow_dispatch

jobs:
  test-workflow:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: repo

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

        # envs like ACTIONS_RUNTIME_TOKEN are not exported for inline steps
      - uses: lhwdev-org/extra-actions/passthrough-action-envs@main

      - name: Test wow
        run: deno run --no-check=remote --allow-all --unstable --quiet repo/src/task/actions/test.ts
